apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: blipfeed-kv
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:                # copy into a native K8s Secret (optional but handy)
    - secretName: blipfeed-secrets
      type: Opaque
      data:
        - objectName: azure-aks-appgw-pfx-base64     # KV secret name
          key: password               # key inside K8s Secret
  parameters:
    keyvaultName: {{ .Values.keyvault.name | default "kv-primary-sysdesign" }}
    tenantId: {{ .Values.azureTenantId }}
    objects: |
      array:
        - |
          objectName: azure-aks-appgw-pfx-base64
          objectType: secret
    userAssignedIdentityID: {{ .Values.azureWorkloadIdentity.clientId }}
