apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: blipfeed-kv
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    clientID: {{ .Values.azureWorkloadIdentity.clientId }}
    tenantId: {{ .Values.azureTenantId }}
    keyvaultName: {{ .Values.keyvault.name }}
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    objects: |
      array:
        - |
          objectName: azure-aks-appgw-pfx-base64  # Updated to the new KV certificate name
          objectType: cert  # Key change: Treat as certificate for PEM export and splitting
  secretObjects:  # Move this here from values.yaml for direct sync (or keep in values if templated)
    - secretName: blipfeed-tls-secret
      type: kubernetes.io/tls
      data:
        - objectName: azure-aks-appgw-pfx-base64
          key: tls.crt
        - objectName: azure-aks-appgw-pfx-base64
          key: tls.key
    # objects: |
    #   array:
    #     - |
    #       objectName: azure-aks-appgw-pfx-base64
    #       objectType: secret