apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: blipfeed-kv
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    clientID: {{ .Values.azureWorkloadIdentity.clientId }}
    tenantId: {{ .Values.azureTenantId }}
    keyvaultName: {{ .Values.keyvault.name }}
    objects: |
      array:
        - |
          objectName: azure-aks-appgw-pfx-base64
          objectType: secret
