apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: blipfeedfanout-kv
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    clientID: {{ .Values.azureWorkloadIdentity.clientId }}
    tenantId: {{ .Values.azureTenantId }}
    keyvaultName: {{ .Values.keyvault.name }}
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    objects: |
      array:
        - |
          objectName: azure-aks-appgw-chain-pfx-base64
          objectType: secret
        - |
          objectName: azure-aks-appgw-chain-pfx
          objectType: secret
          objectEncoding: base64  # Decodes to binary PFX
          objectFormat: pfx       # Fetches raw PFX binary with full chain
  secretObjects:
    - secretName: blipfeedfanout-tls-secret
      type: kubernetes.io/tls
      data:
        - objectName: azure-aks-appgw-chain-pfx # Splits PEM from cert fetch
          key: tls.crt
        - objectName: azure-aks-appgw-chain-pfx
          key: tls.key
    # objects: |
    #   array:
    #     - |
    #       objectName: azure-aks-appgw-pfx-base64
    #       objectType: secret