# This is a basic workflow to help you get started with Actions

name: Deploy User Interface

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      subscription_id:
        description: 'Target Azure Subscription ID'
        required: true
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-latest
    env:
      AZ_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - uses: actions/checkout@v4

    # (Optional) Sign-in so Az cmdlets inside deploy.ps1 can touch Azure
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id:        ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id:        ${{ secrets.AZURE_TENANT_ID }}
        subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    # Run the script
    - name: Run deploy.ps1
      uses: azure/powershell@v2
      with:
        azPSVersion: "latest"
        inlineScript: |
          ./ui/deploy.ps1
        errorActionPreference: Stop
        failOnStandardError: true      
