# This is a basic workflow to help you get started with Actions

name: Deploy Core Infrastructure

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # (Optional) Sign-in so Az cmdlets inside deploy.ps1 can touch Azure
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}   # service-principal JSON
        enable-AzPSSession: true                  # keeps the session for the next step :contentReference[oaicite:0]{index=0}

    # Run the script
    - name: Run deploy.ps1
      uses: azure/powershell@v2
      with:
        azPSVersion: "latest"
        inlineScript: |
          ./deploy.ps1
        errorActionPreference: Stop
        failOnStandardError: true      
